name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  deployments: write

jobs:
    bench:
      name: Run CI Benchmarks

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - name: Run benchmark
        run: cargo bench | tee output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          summary-always: true
          alert-comment-cc-users: '@javagedes'
